version: '2'
services:
    httpbin:
      build: 'modules/httpbin/.'
      ports:
        - '80:80'
    ngrok:
      image: wernight/ngrok
      ports:
      - "4040:4040"
      links:
        - httpbin
      environment:
        - NGROK_PORT=httpbin:80